services:
  mongo:
    image: mongo:6
    container_name: nexon-mongo
    ports: ["27017:27017"]
    volumes: [ "mongo_data:/data/db" ]
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 5

  rest:
    build:
      context: ./server
      dockerfile: Dockerfile.rest
    container_name: nexon-rest
    environment:
      NEXON_MONGO_URI: mongodb://mongo:27017
      NEXON_MONGO_DB: onnx_platform
      LOG_HEALTH: "1"
    env_file: ./.env
    depends_on:
      mongo:
        condition: service_healthy
    ports: ["8000:8000"]
    healthcheck:
      test: ["CMD", "python", "-c",
             "import urllib.request; urllib.request.urlopen('http://127.0.0.1:8000/healthz'); print('ok')"]
      interval: 10s
      timeout: 3s
      retries: 5

  grpc:
    build:
      context: ./server
      dockerfile: Dockerfile.grpc
    container_name: nexon-grpc
    environment:
      NEXON_MONGO_URI: mongodb://mongo:27017
      NEXON_MONGO_DB: onnx_platform
      GRPC_BIND: 0.0.0.0:50051
      GRPC_MAX_RECV_BYTES: 67108864
      GRPC_MAX_SEND_BYTES: 67108864
      LOG_HEALTH: "1"
    env_file: ./.env
    depends_on:
      mongo:
        condition: service_healthy
    ports: ["50051:50051"]
    healthcheck:
      test: ["CMD", "python", "-m", "grpc_service.grpc_healthcheck", "127.0.0.1:50051", ""]
      interval: 10s
      timeout: 5s
      retries: 5

  envoy:
    image: envoyproxy/envoy:v1.31.2
    container_name: nexon-envoy
    command: ["-c", "/etc/envoy/envoy.yaml", "--mode", "serve", "--log-level", "info"]
    volumes:
      - ./server/envoy/envoy.yaml:/etc/envoy/envoy.yaml:ro
      - ./server/envoy/logs:/var/log/envoy
    depends_on:
      rest:
        condition: service_healthy
      grpc:
        condition: service_healthy
    ports:
      - "8080:8080"
      - "9901:9901"

volumes:
  mongo_data: