# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: inference.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finference.proto\x12\x14nexon.grpc.inference\"i\n\x0ePredictRequest\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12\x15\n\rmodel_version\x18\x02 \x01(\x05\x12,\n\x06inputs\x18\x03 \x03(\x0b\x32\x1c.nexon.grpc.inference.Tensor\"=\n\x0cPredictReply\x12-\n\x07outputs\x18\x01 \x03(\x0b\x32\x1c.nexon.grpc.inference.Tensor\"o\n\x06Tensor\x12\x0c\n\x04\x64ims\x18\x01 \x03(\x03\x12\x31\n\tdata_type\x18\x02 \x01(\x0e\x32\x1e.nexon.grpc.inference.DataType\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x16\n\x0etensor_content\x18\x04 \x01(\x0c*v\n\x08\x44\x61taType\x12\x12\n\x0e\x44T_UNSPECIFIED\x10\x00\x12\x0e\n\nDT_FLOAT32\x10\x01\x12\x0e\n\nDT_FLOAT64\x10\x02\x12\x0c\n\x08\x44T_INT32\x10\x03\x12\x0c\n\x08\x44T_INT64\x10\x04\x12\x0b\n\x07\x44T_BOOL\x10\x05\x12\r\n\tDT_STRING\x10\x06\x32g\n\x10InferenceService\x12S\n\x07Predict\x12$.nexon.grpc.inference.PredictRequest\x1a\".nexon.grpc.inference.PredictReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DATATYPE']._serialized_start=324
  _globals['_DATATYPE']._serialized_end=442
  _globals['_PREDICTREQUEST']._serialized_start=41
  _globals['_PREDICTREQUEST']._serialized_end=146
  _globals['_PREDICTREPLY']._serialized_start=148
  _globals['_PREDICTREPLY']._serialized_end=209
  _globals['_TENSOR']._serialized_start=211
  _globals['_TENSOR']._serialized_end=322
  _globals['_INFERENCESERVICE']._serialized_start=444
  _globals['_INFERENCESERVICE']._serialized_end=547
# @@protoc_insertion_point(module_scope)
